workflows:
  android-workflow:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

  ios-workflow:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Pod install
        script: |
          cd ios
          pod install
      - name: Build iOS IPA
        script: |
          flutter build ipa \
            --release \
            --export-options-plist=/users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
